## Homework #1 Demo

## Imports 

In [53]:
import pandas as pd
import numpy as np

## Data

In [76]:
df = pd.read_excel('data/single_name_return_data.xlsx', sheet_name = 'excess returns')

df = df.set_index('Date')

df.head()

AAPL      AMZN        BA       BAC         C       CVX  \
Date                                                                     
2012-07-31  0.045822  0.021677 -0.005249 -0.102690 -0.010215  0.038673   
2012-08-31  0.093695  0.063985 -0.028348  0.088374  0.095325  0.031557   
2012-09-30  0.002878  0.024450 -0.025129  0.106596  0.101394  0.039311   
2012-10-31 -0.107527 -0.084191  0.012142  0.055565  0.142799 -0.054148   
2012-11-30 -0.012465  0.082180  0.060905  0.057849 -0.075265 -0.033098   

                 DUK       EOG        FB        GS  ...        MS      MSFT  \
Date                                                ...                       
2012-07-31 -0.020237  0.089705 -0.301929  0.052576  ... -0.060127 -0.036613   
2012-08-31 -0.033600  0.104808 -0.168307  0.052194  ...  0.097915  0.052556   
2012-09-30  0.000236  0.034708  0.199417  0.075375  ...  0.116082 -0.034312   
2012-10-31  0.013964  0.041325 -0.025320  0.076691  ...  0.041360 -0.040922   
2012-11-30 -0.016422  0.009610  0.326295 -0.033595  ... -0.029435 -0.059700   

                 NEE       PFE       SPY       TMO       UNH       UPS  \
Date                                                                     
2012-07-31  0.030373  0.045217  0.011829  0.072433 -0.126667 -0.039995   
2012-08-31 -0.042413  0.001498  0.024871  0.029996  0.062649 -0.016667   
2012-09-30  0.044948  0.041574  0.025433  0.028141  0.024657 -0.030267   
2012-10-31 -0.003766  0.000878 -0.018126  0.037979  0.010721  0.023546   
2012-11-30 -0.010606  0.014977  0.005569  0.040689 -0.028841  0.006157   

                   V       XOM  
Date                            
2012-07-31  0.044002  0.014959  
2012-08-31 -0.004849  0.011533  
2012-09-30  0.047099  0.047618  
2012-10-31  0.033436 -0.002989  
2012-11-30  0.081328 -0.027273  

[5 rows x 23 columns]

## Annualizing Statistics

**Mean:**

In [55]:
df.mean()

AAPL    0.021600
AMZN    0.028017
BA      0.017154
BAC     0.019032
C       0.013459
CVX     0.005109
DUK     0.007360
EOG     0.011653
FB      0.027120
GS      0.016337
HON     0.015525
JNJ     0.010969
JPM     0.017508
MS      0.021420
MSFT    0.023301
NEE     0.016447
PFE     0.009330
SPY     0.012451
TMO     0.022671
UNH     0.020252
UPS     0.013201
V       0.020446
XOM     0.002280
dtype: float64

In [57]:
df.mean() * 12

AAPL    0.259205
AMZN    0.336201
BA      0.205842
BAC     0.228383
C       0.161503
CVX     0.061303
DUK     0.088318
EOG     0.139833
FB      0.325445
GS      0.196038
HON     0.186298
JNJ     0.131622
JPM     0.210101
MS      0.257045
MSFT    0.279613
NEE     0.197365
PFE     0.111958
SPY     0.149408
TMO     0.272047
UNH     0.243024
UPS     0.158406
V       0.245350
XOM     0.027361
dtype: float64

**Volatility:**

In [58]:
df.std() * np.sqrt(12)

AAPL    0.279050
AMZN    0.279784
BA      0.348904
BAC     0.284569
C       0.311798
CVX     0.243849
DUK     0.160053
EOG     0.366468
FB      0.356598
GS      0.267811
HON     0.176032
JNJ     0.149931
JPM     0.224585
MS      0.283784
MSFT    0.199279
NEE     0.158966
PFE     0.188054
SPY     0.131007
TMO     0.194228
UNH     0.195243
UPS     0.234644
V       0.185883
XOM     0.235791
dtype: float64

**Sharpe:**

In [7]:
Sharpe = df.mean() / df.std()

Sharpe * np.sqrt(12)

AAPL    0.928884
AMZN    1.201647
BA      0.589968
BAC     0.802556
C       0.517974
CVX     0.251398
DUK     0.551808
EOG     0.381570
FB      0.912639
GS      0.732003
HON     1.058323
JNJ     0.877887
JPM     0.935506
MS      0.905779
MSFT    1.403125
NEE     1.241558
PFE     0.595349
SPY     1.140462
TMO     1.400660
UNH     1.244726
UPS     0.675093
V       1.319916
XOM     0.116039
dtype: float64

**Functionalize code:**

In [59]:
def stats(data, annualize_factor):
    mean = ...
    vol = ... .std()
    sharpe = mean / vol
    
    df = pd.DataFrame(...)
    
    return df

**Covariance matrix:**

In [11]:
Sigma = df.cov()

Sigma

AAPL      AMZN        BA       BAC         C       CVX       DUK  \
AAPL  0.006489  0.002922  0.001817  0.001552  0.002158  0.001084  0.000088   
AMZN  0.002922  0.006523  0.001917  0.001780  0.002179  0.001295  0.000074   
BA    0.001817  0.001917  0.010145  0.003736  0.005476  0.003433  0.000390   
BAC   0.001552  0.001780  0.003736  0.006748  0.006220  0.003075 -0.000154   
C     0.002158  0.002179  0.005476  0.006220  0.008102  0.004226  0.000015   
CVX   0.001084  0.001295  0.003433  0.003075  0.004226  0.004955  0.000372   
DUK   0.000088  0.000074  0.000390 -0.000154  0.000015  0.000372  0.002135   
EOG   0.001641  0.002323  0.005170  0.004871  0.006327  0.006133  0.000133   
FB    0.002230  0.002974  0.002039  0.002457  0.002234  0.001422  0.000635   
GS    0.001995  0.001395  0.003542  0.004990  0.005802  0.003284 -0.000119   
HON   0.001359  0.001461  0.003340  0.002502  0.003361  0.002176  0.000489   
JNJ   0.001127  0.001182  0.001076  0.001229  0.001767  0.001381  0.000859   
JPM   0.001078  0.001238  0.002994  0.004586  0.005067  0.002804 -0.000082   
MS    0.001944  0.001923  0.004046  0.005521  0.006209  0.003414 -0.000194   
MSFT  0.002202  0.002247  0.001364  0.001712  0.001895  0.001429  0.000025   
NEE   0.000521  0.000390  0.000013 -0.000466 -0.000441 -0.000099  0.001478   
PFE   0.000775  0.001743  0.000951  0.001516  0.001791  0.001550  0.000711   
SPY   0.001776  0.001805  0.002153  0.002082  0.002571  0.001877  0.000369   
TMO   0.001351  0.002493  0.000914  0.001160  0.001396  0.000804  0.000494   
UNH   0.001074  0.001294  0.001183  0.002014  0.002083  0.001446  0.000317   
UPS   0.001633  0.001748  0.001745  0.001969  0.002209  0.001515  0.000398   
V     0.001749  0.002278  0.002589  0.001800  0.002351  0.001629  0.000126   
XOM   0.001322  0.001397  0.003225  0.002881  0.004028  0.004117  0.000289   

           EOG        FB        GS  ...        MS      MSFT       NEE  \
AAPL  0.001641  0.002230  0.001995  ...  0.001944  0.002202  0.000521   
AMZN  0.002323  0.002974  0.001395  ...  0.001923  0.002247  0.000390   
BA    0.005170  0.002039  0.003542  ...  0.004046  0.001364  0.000013   
BAC   0.004871  0.002457  0.004990  ...  0.005521  0.001712 -0.000466   
C     0.006327  0.002234  0.005802  ...  0.006209  0.001895 -0.000441   
CVX   0.006133  0.001422  0.003284  ...  0.003414  0.001429 -0.000099   
DUK   0.000133  0.000635 -0.000119  ... -0.000194  0.000025  0.001478   
EOG   0.011192  0.003047  0.004913  ...  0.005233  0.001511 -0.000541   
FB    0.003047  0.010597  0.001831  ...  0.002278  0.000727  0.000615   
GS    0.004913  0.001831  0.005977  ...  0.005596  0.001452 -0.000438   
HON   0.003177  0.001478  0.002374  ...  0.002643  0.000924  0.000345   
JNJ   0.001660  0.000837  0.001322  ...  0.001292  0.000875  0.000768   
JPM   0.003904  0.001143  0.004246  ...  0.004582  0.001375 -0.000237   
MS    0.005233  0.002278  0.005596  ...  0.006711  0.001763 -0.000453   
MSFT  0.001511  0.000727  0.001452  ...  0.001763  0.003309  0.000102   
NEE  -0.000541  0.000615 -0.000438  ... -0.000453  0.000102  0.002106   
PFE   0.001789  0.001097  0.001224  ...  0.001413  0.000472  0.000677   
SPY   0.002638  0.001641  0.002091  ...  0.002248  0.001234  0.000337   
TMO   0.001131  0.001899  0.001076  ...  0.001287  0.001078  0.000659   
UNH   0.001864  0.001655  0.001405  ...  0.001643  0.000476  0.000128   
UPS   0.001726  0.001222  0.001752  ...  0.001978  0.001263  0.000385   
V     0.002271  0.001842  0.001883  ...  0.002006  0.001440  0.000266   
XOM   0.005845  0.001455  0.003264  ...  0.003208  0.001264 -0.000020   

           PFE       SPY       TMO       UNH       UPS         V       XOM  
AAPL  0.000775  0.001776  0.001351  0.001074  0.001633  0.001749  0.001322  
AMZN  0.001743  0.001805  0.002493  0.001294  0.001748  0.002278  0.001397  
BA    0.000951  0.002153  0.000914  0.001183  0.001745  0.002589  0.003225  
BAC   0.001516  0.002082  0.001160  0.002014  0.001969  0.001800  0.002881  

**Matrix Operations:**

In [12]:
Sigma.shape

(23, 23)

Matrix of ones:

In [82]:
N = Sigma.shape

np.ones(N)

(23, 23)

In [80]:
np.ones(N).shape

(23, 23)

In [21]:
np.ones(10).shape

(10,)

In [20]:
np.ones((1,10)).shape

(1, 10)

Diagonalize:

In [74]:
Sigma

AAPL      AMZN        BA       BAC         C       CVX       DUK  \
AAPL  0.006489  0.002922  0.001817  0.001552  0.002158  0.001084  0.000088   
AMZN  0.002922  0.006523  0.001917  0.001780  0.002179  0.001295  0.000074   
BA    0.001817  0.001917  0.010145  0.003736  0.005476  0.003433  0.000390   
BAC   0.001552  0.001780  0.003736  0.006748  0.006220  0.003075 -0.000154   
C     0.002158  0.002179  0.005476  0.006220  0.008102  0.004226  0.000015   
CVX   0.001084  0.001295  0.003433  0.003075  0.004226  0.004955  0.000372   
DUK   0.000088  0.000074  0.000390 -0.000154  0.000015  0.000372  0.002135   
EOG   0.001641  0.002323  0.005170  0.004871  0.006327  0.006133  0.000133   
FB    0.002230  0.002974  0.002039  0.002457  0.002234  0.001422  0.000635   
GS    0.001995  0.001395  0.003542  0.004990  0.005802  0.003284 -0.000119   
HON   0.001359  0.001461  0.003340  0.002502  0.003361  0.002176  0.000489   
JNJ   0.001127  0.001182  0.001076  0.001229  0.001767  0.001381  0.000859   
JPM   0.001078  0.001238  0.002994  0.004586  0.005067  0.002804 -0.000082   
MS    0.001944  0.001923  0.004046  0.005521  0.006209  0.003414 -0.000194   
MSFT  0.002202  0.002247  0.001364  0.001712  0.001895  0.001429  0.000025   
NEE   0.000521  0.000390  0.000013 -0.000466 -0.000441 -0.000099  0.001478   
PFE   0.000775  0.001743  0.000951  0.001516  0.001791  0.001550  0.000711   
SPY   0.001776  0.001805  0.002153  0.002082  0.002571  0.001877  0.000369   
TMO   0.001351  0.002493  0.000914  0.001160  0.001396  0.000804  0.000494   
UNH   0.001074  0.001294  0.001183  0.002014  0.002083  0.001446  0.000317   
UPS   0.001633  0.001748  0.001745  0.001969  0.002209  0.001515  0.000398   
V     0.001749  0.002278  0.002589  0.001800  0.002351  0.001629  0.000126   
XOM   0.001322  0.001397  0.003225  0.002881  0.004028  0.004117  0.000289   

           EOG        FB        GS  ...        MS      MSFT       NEE  \
AAPL  0.001641  0.002230  0.001995  ...  0.001944  0.002202  0.000521   
AMZN  0.002323  0.002974  0.001395  ...  0.001923  0.002247  0.000390   
BA    0.005170  0.002039  0.003542  ...  0.004046  0.001364  0.000013   
BAC   0.004871  0.002457  0.004990  ...  0.005521  0.001712 -0.000466   
C     0.006327  0.002234  0.005802  ...  0.006209  0.001895 -0.000441   
CVX   0.006133  0.001422  0.003284  ...  0.003414  0.001429 -0.000099   
DUK   0.000133  0.000635 -0.000119  ... -0.000194  0.000025  0.001478   
EOG   0.011192  0.003047  0.004913  ...  0.005233  0.001511 -0.000541   
FB    0.003047  0.010597  0.001831  ...  0.002278  0.000727  0.000615   
GS    0.004913  0.001831  0.005977  ...  0.005596  0.001452 -0.000438   
HON   0.003177  0.001478  0.002374  ...  0.002643  0.000924  0.000345   
JNJ   0.001660  0.000837  0.001322  ...  0.001292  0.000875  0.000768   
JPM   0.003904  0.001143  0.004246  ...  0.004582  0.001375 -0.000237   
MS    0.005233  0.002278  0.005596  ...  0.006711  0.001763 -0.000453   
MSFT  0.001511  0.000727  0.001452  ...  0.001763  0.003309  0.000102   
NEE  -0.000541  0.000615 -0.000438  ... -0.000453  0.000102  0.002106   
PFE   0.001789  0.001097  0.001224  ...  0.001413  0.000472  0.000677   
SPY   0.002638  0.001641  0.002091  ...  0.002248  0.001234  0.000337   
TMO   0.001131  0.001899  0.001076  ...  0.001287  0.001078  0.000659   
UNH   0.001864  0.001655  0.001405  ...  0.001643  0.000476  0.000128   
UPS   0.001726  0.001222  0.001752  ...  0.001978  0.001263  0.000385   
V     0.002271  0.001842  0.001883  ...  0.002006  0.001440  0.000266   
XOM   0.005845  0.001455  0.003264  ...  0.003208  0.001264 -0.000020   

           PFE       SPY       TMO       UNH       UPS         V       XOM  
AAPL  0.000775  0.001776  0.001351  0.001074  0.001633  0.001749  0.001322  
AMZN  0.001743  0.001805  0.002493  0.001294  0.001748  0.002278  0.001397  
BA    0.000951  0.002153  0.000914  0.001183  0.001745  0.002589  0.003225  
BAC   0.001516  0.002082  0.001160  0.002014  0.001969  0.001800  0.002881  

In [73]:
np.diag(Sigma)

array([0.0064891 , 0.00652324, 0.01014452, 0.00674831, 0.0081015 ,
       0.00495518, 0.00213474, 0.01119158, 0.01059683, 0.00597688,
       0.00258226, 0.00187327, 0.00420322, 0.0067111 , 0.00330934,
       0.00210584, 0.00294703, 0.00143023, 0.0031437 , 0.00317665,
       0.00458813, 0.00287937, 0.00463314])

In [75]:
np.diag(np.diag(Sigma))

array([[0.0064891 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.00652324, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.01014452, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.006

Reshape:

In [23]:
mat = np.ones((1,10)).reshape((2,5))

mat

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Transpose:

In [69]:
mat.T

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

Stack:

In [83]:
df.cov().stack()

AAPL  AAPL    0.006489
      AMZN    0.002922
      BA      0.001817
      BAC     0.001552
      C       0.002158
                ...   
XOM   TMO     0.000897
      UNH     0.001225
      UPS     0.001483
      V       0.001650
      XOM     0.004633
Length: 529, dtype: float64

In [84]:
df.cov().stack().unstack()

AAPL      AMZN        BA       BAC         C       CVX       DUK  \
AAPL  0.006489  0.002922  0.001817  0.001552  0.002158  0.001084  0.000088   
AMZN  0.002922  0.006523  0.001917  0.001780  0.002179  0.001295  0.000074   
BA    0.001817  0.001917  0.010145  0.003736  0.005476  0.003433  0.000390   
BAC   0.001552  0.001780  0.003736  0.006748  0.006220  0.003075 -0.000154   
C     0.002158  0.002179  0.005476  0.006220  0.008102  0.004226  0.000015   
CVX   0.001084  0.001295  0.003433  0.003075  0.004226  0.004955  0.000372   
DUK   0.000088  0.000074  0.000390 -0.000154  0.000015  0.000372  0.002135   
EOG   0.001641  0.002323  0.005170  0.004871  0.006327  0.006133  0.000133   
FB    0.002230  0.002974  0.002039  0.002457  0.002234  0.001422  0.000635   
GS    0.001995  0.001395  0.003542  0.004990  0.005802  0.003284 -0.000119   
HON   0.001359  0.001461  0.003340  0.002502  0.003361  0.002176  0.000489   
JNJ   0.001127  0.001182  0.001076  0.001229  0.001767  0.001381  0.000859   
JPM   0.001078  0.001238  0.002994  0.004586  0.005067  0.002804 -0.000082   
MS    0.001944  0.001923  0.004046  0.005521  0.006209  0.003414 -0.000194   
MSFT  0.002202  0.002247  0.001364  0.001712  0.001895  0.001429  0.000025   
NEE   0.000521  0.000390  0.000013 -0.000466 -0.000441 -0.000099  0.001478   
PFE   0.000775  0.001743  0.000951  0.001516  0.001791  0.001550  0.000711   
SPY   0.001776  0.001805  0.002153  0.002082  0.002571  0.001877  0.000369   
TMO   0.001351  0.002493  0.000914  0.001160  0.001396  0.000804  0.000494   
UNH   0.001074  0.001294  0.001183  0.002014  0.002083  0.001446  0.000317   
UPS   0.001633  0.001748  0.001745  0.001969  0.002209  0.001515  0.000398   
V     0.001749  0.002278  0.002589  0.001800  0.002351  0.001629  0.000126   
XOM   0.001322  0.001397  0.003225  0.002881  0.004028  0.004117  0.000289   

           EOG        FB        GS  ...        MS      MSFT       NEE  \
AAPL  0.001641  0.002230  0.001995  ...  0.001944  0.002202  0.000521   
AMZN  0.002323  0.002974  0.001395  ...  0.001923  0.002247  0.000390   
BA    0.005170  0.002039  0.003542  ...  0.004046  0.001364  0.000013   
BAC   0.004871  0.002457  0.004990  ...  0.005521  0.001712 -0.000466   
C     0.006327  0.002234  0.005802  ...  0.006209  0.001895 -0.000441   
CVX   0.006133  0.001422  0.003284  ...  0.003414  0.001429 -0.000099   
DUK   0.000133  0.000635 -0.000119  ... -0.000194  0.000025  0.001478   
EOG   0.011192  0.003047  0.004913  ...  0.005233  0.001511 -0.000541   
FB    0.003047  0.010597  0.001831  ...  0.002278  0.000727  0.000615   
GS    0.004913  0.001831  0.005977  ...  0.005596  0.001452 -0.000438   
HON   0.003177  0.001478  0.002374  ...  0.002643  0.000924  0.000345   
JNJ   0.001660  0.000837  0.001322  ...  0.001292  0.000875  0.000768   
JPM   0.003904  0.001143  0.004246  ...  0.004582  0.001375 -0.000237   
MS    0.005233  0.002278  0.005596  ...  0.006711  0.001763 -0.000453   
MSFT  0.001511  0.000727  0.001452  ...  0.001763  0.003309  0.000102   
NEE  -0.000541  0.000615 -0.000438  ... -0.000453  0.000102  0.002106   
PFE   0.001789  0.001097  0.001224  ...  0.001413  0.000472  0.000677   
SPY   0.002638  0.001641  0.002091  ...  0.002248  0.001234  0.000337   
TMO   0.001131  0.001899  0.001076  ...  0.001287  0.001078  0.000659   
UNH   0.001864  0.001655  0.001405  ...  0.001643  0.000476  0.000128   
UPS   0.001726  0.001222  0.001752  ...  0.001978  0.001263  0.000385   
V     0.002271  0.001842  0.001883  ...  0.002006  0.001440  0.000266   
XOM   0.005845  0.001455  0.003264  ...  0.003208  0.001264 -0.000020   

           PFE       SPY       TMO       UNH       UPS         V       XOM  
AAPL  0.000775  0.001776  0.001351  0.001074  0.001633  0.001749  0.001322  
AMZN  0.001743  0.001805  0.002493  0.001294  0.001748  0.002278  0.001397  
BA    0.000951  0.002153  0.000914  0.001183  0.001745  0.002589  0.003225  
BAC   0.001516  0.002082  0.001160  0.002014  0.001969  0.001800  0.002881  

Dot product:

In [36]:
df.mean() @ np.ones((23,)) 

0.37263938048752765

In [42]:
df.mean() @ ((np.ones(23)) / len(df.mean()))

0.0162017121951099

What is this?

In [43]:
type(df.mean())

pandas.core.series.Series

**Inverting a matrix:**

In [44]:
np.linalg.inv(Sigma)

array([[ 4.13088814e+02,  3.12829417e+01,  3.35094415e+01,
         5.97825025e+01, -6.12499520e+01,  1.46293229e+02,
         1.42281462e+02,  3.37850230e+01,  1.40917617e+01,
        -2.58615230e+01,  1.27624803e+02, -5.81360269e+00,
         1.74936942e+02,  5.66258120e+01, -3.45657889e+01,
        -5.65225147e+00,  7.56015145e+01, -1.68174189e+03,
         1.32302251e+02, -5.91979023e+00,  7.88611730e+01,
         7.35154265e+01,  8.48238912e+01],
       [ 3.12829417e+01,  3.94136845e+02,  3.83578765e+00,
         4.21789248e+01, -5.65748439e+01,  1.39517398e+02,
         7.59354462e+01, -5.24753982e+01, -8.63329763e+00,
         1.46415066e+02,  2.27732933e+02,  1.69781158e+01,
         1.90109565e+01, -3.05946073e+00, -5.57265981e+01,
         5.90100154e+01, -6.79541046e+01, -9.65299406e+02,
        -8.07201040e+01,  1.20590954e+00,  3.87074286e+01,
        -1.06965978e+02,  7.41759015e+01],
       [ 3.35094415e+01,  3.83578765e+00,  2.19410036e+02,
         2.11994536e+00, -1.2

**Functionalize code:**

In [49]:
def compute_tangency(df):
    
    # ... formulas ...
    
    omega_tan = ...
    
    return omega_tan

In [51]:
def target_mv_portfolio(df, target_mu):
    
    # call compute_tangency
    
    # ... formulas ...
    
    scaling_factor = target_mu * ...
    
    omega_star = scaling_factor * omega_tan
    
    return omega_star

In [52]:
def portfolio_stats(weights, mu_vector, Sigma, annualize_factor):
    
    mean = ...
    
    vol = ...
    
    sharpe = ...
    
    return pd.DataFrame(data = [mean, vol, sharpe])